openapi: 3.0.3
info:
  title: DCAT-AP-NO validator service
  description: The service validates a graph against dcat-ap-no specification
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://digdir.no'
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
servers:
  - url: https://validator.staging.fellesdatakatalog.digdir
paths:
  /validator:
    post:
      description: Validates RDF graph and generates a validation report
      requestBody:
        description: A Multipart/form-data body containing one or more of the following parts
        content:
          multipart/form-data:
            schema:
              type: object
              properties: # Request parts
                  config:
                    $ref: '#/components/schemas/Config'
                  text:
                    type: string
                    description: a text string with serialized RDF
                  url:
                    type: string
                    format: uri
                    description: a url pointing to an RDF graph on the internet
                  file:
                    type: string
                    format: binary
                    description: a file containing serialized RDF
            encoding:
              file:
                contentType: text/turtle
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
  /shapes:
    get:
      description: returns a list of shape graphs the validator can execute
      responses:
        200:
          description: OK
          content:
            text/turtle:
              schema:
                type: string
  /shapes/{id}:
    get:
      description: returns the content of a shape graph given by id
      parameters:
      - name: id
        in: path
        description: shape id
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            text/turtle:
              schema:
                type: string
components:
  schemas:
    Config:
      type: object
      properties:
        shapeId:
          type: string
          default: "2"
          description: an identifier of the set of rules (shapes) to be validated against
        expand:
          type: boolean
          default: false
          description: whether service should fetch remote triples referenced by input graph
        includeExpandedTriples:
          type: boolean
          default: false
          description: whether service should return remote triples referenced by input graph
